# Generated by Django 3.0.3 on 2020-03-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='postcode',
            field=models.IntegerField(default=0),
        ),
    ]
