# Generated by Django 3.0.3 on 2020-03-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200315_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='postcode',
            field=models.CharField(max_length=6),
        ),
    ]
