# Generated by Django 3.0.3 on 2020-03-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0003_auto_20200322_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
