# Generated by Django 3.0.3 on 2020-04-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_account_user_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
