# Generated by Django 3.0.3 on 2020-03-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_available',
            field=models.IntegerField(),
        ),
    ]
