# Generated by Django 3.0.3 on 2020-03-15 22:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200315_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'category_1'), (2, 'category_2'), (3, 'category_3'), (4, 'category_4'), (5, 'category_5')], default=1, max_length=9),
        ),
    ]
