# Generated by Django 3.0.3 on 2020-03-16 20:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'kawy'), (2, 'fartuchy'), (3, 'akcesoria'), (5, 'inne')], default=1, max_length=7),
        ),
    ]
