# Generated by Django 3.0.3 on 2020-03-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_orderitem_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(default='product detail description'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='product list description'),
        ),
    ]
