# Generated by Django 3.0.3 on 2020-04-06 17:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_order_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=False, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=multiselectfield.db.fields.MultiSelectField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(default=False, max_length=6),
        ),
    ]
