# Generated by Django 3.0.3 on 2020-04-07 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0008_order_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
    ]
