# Generated by Django 3.0.3 on 2020-04-08 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0010_order_is_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_option', models.CharField(max_length=30)),
                ('option_price', models.IntegerField()),
                ('pre_paid', models.BooleanField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping_cart.Order')),
            ],
        ),
    ]
