# Generated by Django 3.0.3 on 2020-04-08 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0012_auto_20200408_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_option',
            new_name='option',
        ),
    ]
