# Generated by Django 3.0.3 on 2020-04-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0015_auto_20200410_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='option_price',
            field=models.IntegerField(),
        ),
    ]
