# Generated by Django 3.0.3 on 2020-04-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0016_auto_20200410_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
